import logging
from prometheus_client import REGISTRY
import httpx
from app.core.config import DISCORD_WEBHOOK_URL, APP_ENV

logger = logging.getLogger(__name__)

async def _acquire_distributed_lock(lock_key: str, ttl_seconds: int = 60) -> bool:
    """
    다중 인스턴스 스케줄러 중복 실행 방지를 위한 분산 락 획득
    (실제 프로덕션 환경에선 Redis SETNX 또는 DB Row Lock을 연동해야 합니다.)
    """
    # TODO: Redis / DB Lock 연동
    return True

async def send_discord_report():
    """
    Prometheus in-memory REGISTRY를 분석하여 지난 24시간(실질적으로 프로세스 기동 후 누적)
    통계를 계산하고, Discord 웹훅으로 전송합니다.
    """
    if not DISCORD_WEBHOOK_URL:
        logger.warning("Discord webhook URL is not set. Skipping daily report.")
        return
        
    # 다중 인스턴스 중복 실행 방지 (분산 락 획득)
    if not await _acquire_distributed_lock("daily_discord_report_lock"):
        logger.info("Another instance is running the daily report. Skipping...")
        return

    # 1. 지표 초기화
    total_requests = 0
    total_errors = 0   # 500대 에러
    total_duration = 0.0

    try:
        # 2. Prometheus REGISTRY 분석
        for metric in REGISTRY.collect():
            for sample in metric.samples:
                if sample.name == "http_requests_total":
                    # sample.labels['status_code']로 접근
                    total_requests += sample.value
                    if str(sample.labels.get('status_code', '')).startswith('5'):
                        total_errors += sample.value
                elif sample.name == "http_request_duration_seconds_sum":
                    # Histogram의 sum을 통해 총 지연 시간 획득
                    total_duration += sample.value
                    
        # 3. 통계 산출
        avg_latency = (total_duration / total_requests) if total_requests > 0 else 0
        uptime_percent = ((total_requests - total_errors) / total_requests * 100) if total_requests > 0 else 100.0
        
        # 4. 디스코드 메시지 포맷팅
        env_label = APP_ENV.upper()
        message = {
            "content": None,
            "embeds": [
                {
                    "title": f"📊 픽합주 데일리 헬스체크 리포트 [{env_label}]",
                    "description": "최근 수집된 모니터링 메트릭 요약 결과입니다. (서버 기동 후 누적 데이터 기준)",
                    "color": 65280 if uptime_percent >= 99.0 else 16711680,
                    "fields": [
                        {
                            "name": "성공/총 요청 수",
                            "value": f"{int(total_requests - total_errors)} / {int(total_requests)}",
                            "inline": True
                        },
                        {
                            "name": "50x 에러 발생 횟수",
                            "value": f"{int(total_errors)}회",
                            "inline": True
                        },
                        {
                            "name": "요청 성공률 (Success Rate)",
                            "value": f"{uptime_percent:.2f}%",
                            "inline": True
                        },
                        {
                            "name": "평균 응답 지연 (Latency)",
                            "value": f"{avg_latency:.3f}초",
                            "inline": True
                        }
                    ],
                    "footer": {
                        "text": "Generated by Monitoring Service"
                    }
                }
            ]
        }
        
        # 5. 웹훅 발송 (타임아웃은 길게 설정하지 않음)
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.post(DISCORD_WEBHOOK_URL, json=message)
            resp.raise_for_status()
            logger.info("Successfully sent daily report to Discord.")
            
    except Exception as e:
        logger.error(f"Failed to generate or send daily report: {e}", exc_info=True)
