version: 0.0
os: linux

files:
  # CodeDeploy 번들의 모든 내용(Git 리포지토리의 루트)을 EC2 인스턴스의 /home/ubuntu/app 디렉토리로 복사합니다.
  # 'source: /'는 CodeDeploy가 압축 해제한 번들의 최상위 디렉토리를 의미합니다.
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes # 기존 파일이 있다면 새 파일로 덮어씁니다.

permissions:
  # /home/ubuntu/app 디렉토리 및 그 하위의 모든 파일/디렉토리에 대한 권한을 설정합니다.
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    type:
      - file
      - directory
    mode: 755 # 실행 권한(755)을 명시적으로 부여하여 스크립트 실행이 가능하도록 합니다.

hooks:
  ApplicationStart:
    # deploy.sh 스크립트의 위치는 destination이 /home/ubuntu/app 이므로,
    # /home/ubuntu/app/scripts/deploy.sh가 됩니다.
    - location: scripts/deploy.sh
      timeout: 600 # 스크립트 실행 최대 시간 (초)
      runas: ubuntu # 이 스크립트를 'ubuntu' 사용자로 실행합니다.