"""
GCP Cloud Function: 헬스체크 모니터링 데일리 리포트
Cloud Logging API로 지난 24시간 /health, /ping 로그를 분석하여 Discord로 리포트를 전송합니다.

Trigger: Cloud Scheduler (매일 09:00 KST, OIDC 인증)
"""

import os
import json
import logging
import datetime

import functions_framework
import httpx
from google.cloud import logging as cloud_logging

logger = logging.getLogger(__name__)

# ── 환경 변수 ──────────────────────────────────────────
DISCORD_WEBHOOK_URL = os.environ["DISCORD_WEBHOOK_URL"]
GCP_PROJECT_ID = os.environ["GCP_PROJECT_ID"]
CLOUD_RUN_SERVICE_NAME = os.environ["CLOUD_RUN_SERVICE_NAME"]
APP_ENV = os.environ.get("APP_ENV", "production")


def _query_health_logs(hours: int = 24) -> dict:
    """
    Cloud Logging API로 지난 N시간의 /health, /ping 엔드포인트 로그를 조회하여
    총 요청 수, 5xx 에러 수, 총 레이턴시를 계산합니다.

    FastAPI RealIPMiddleware가 기록하는 구조화 필드:
    - jsonPayload.path: "/health" 또는 "/ping"
    - jsonPayload.status_code: HTTP 응답 코드 (int)
    - jsonPayload.latency_sec: 처리 시간 (float, 초)
    """
    client = cloud_logging.Client(project=GCP_PROJECT_ID)

    now = datetime.datetime.now(datetime.timezone.utc)
    since = now - datetime.timedelta(hours=hours)

    # RFC 3339 형식으로 변환 (Cloud Logging API 요구사항)
    since_str = since.strftime("%Y-%m-%dT%H:%M:%SZ")
    now_str = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    # Cloud Logging 필터
    # NOTE: logName은 stdout/stderr 모두 가능하므로 제한하지 않습니다.
    # NOTE: severity는 JSON 구조 로그에서 None일 수 있으므로 제한하지 않습니다.
    # resource.type + service_name + jsonPayload.path 필터만으로 충분합니다.
    #
    # RealIPMiddleware는 헬스체크 요청을 성공/실패 모두 로깅합니다.
    # (2xx → INFO, 5xx → ERROR)
    log_filter = f"""
        resource.type="cloud_run_revision"
        resource.labels.service_name="{CLOUD_RUN_SERVICE_NAME}"
        timestamp >= "{since_str}"
        timestamp <= "{now_str}"
        jsonPayload.path=("/health" OR "/ping")
    """.strip()

    total_requests = 0
    total_errors = 0
    total_latency = 0.0

    for entry in client.list_entries(filter_=log_filter, page_size=1000):
        payload = entry.payload  # jsonPayload가 dict로 파싱됨
        if not isinstance(payload, dict):
            continue

        total_requests += 1

        # NOTE: Cloud Logging Python 클라이언트는 JSON 숫자를 float로 파싱합니다.
        # (예: status_code 503 → 503.0)
        # 따라서 int()로 변환 후 비교합니다.
        raw_status = payload.get("status_code", 200)
        try:
            status_code = int(raw_status)
        except (ValueError, TypeError):
            status_code = 0

        if status_code >= 500:
            total_errors += 1

        latency = payload.get("latency_sec", 0.0)
        try:
            total_latency += float(latency)
        except (ValueError, TypeError):
            pass

    return {
        "total_requests": total_requests,
        "total_errors": total_errors,
        "total_latency": total_latency,
    }


def _build_discord_embed(stats: dict) -> dict:
    """Discord 웹훅용 Embed 메시지를 생성합니다."""
    total_requests = stats["total_requests"]
    total_errors = stats["total_errors"]
    total_latency = stats["total_latency"]

    avg_latency = (total_latency / total_requests) if total_requests > 0 else 0
    uptime_percent = (
        ((total_requests - total_errors) / total_requests * 100)
        if total_requests > 0
        else 100.0
    )

    env_label = APP_ENV.upper()

    return {
        "content": None,
        "embeds": [
            {
                "title": f"📊 픽합주 헬스체크 모니터링 리포트 [{env_label}]",
                "description": "최근 24시간 Cloud Logging 기반 모니터링 메트릭 요약 결과입니다.",
                "color": 65280 if uptime_percent >= 99.0 else 16711680,
                "fields": [
                    {
                        "name": "성공/총 요청 수",
                        "value": f"{total_requests - total_errors} / {total_requests}",
                        "inline": True,
                    },
                    {
                        "name": "50x 에러 발생 횟수",
                        "value": f"{total_errors}회",
                        "inline": True,
                    },
                    {
                        "name": "요청 성공률 (Success Rate)",
                        "value": f"{uptime_percent:.2f}%",
                        "inline": True,
                    },
                    {
                        "name": "평균 응답 지연 (Latency)",
                        "value": f"{avg_latency:.3f}초",
                        "inline": True,
                    },
                ],
                "footer": {
                    "text": "Generated by Cloud Function — health-check-reporter",
                },
            }
        ],
    }


def _send_to_discord(message: dict) -> None:
    """Discord 웹훅으로 메시지를 전송합니다."""
    with httpx.Client(timeout=10.0) as client:
        resp = client.post(DISCORD_WEBHOOK_URL, json=message)
        resp.raise_for_status()


@functions_framework.http
def health_check_reporter(request):
    """
    Cloud Scheduler에서 호출하는 HTTP 핸들러입니다.
    Cloud Logging API로 지난 24시간 헬스체크 로그를 분석하고 Discord로 리포트를 전송합니다.
    """
    try:
        stats = _query_health_logs(hours=24)
        message = _build_discord_embed(stats)
        _send_to_discord(message)

        return (
            json.dumps(
                {
                    "ok": True,
                    "stats": {
                        "total_requests": stats["total_requests"],
                        "total_errors": stats["total_errors"],
                        "avg_latency": round(
                            stats["total_latency"] / max(stats["total_requests"], 1), 3
                        ),
                    },
                }
            ),
            200,
            {"Content-Type": "application/json"},
        )

    except Exception as e:
        logger.error(f"Health check report failed: {e}", exc_info=True)
        return (
            json.dumps({"ok": False, "error": str(e)}),
            500,
            {"Content-Type": "application/json"},
        )
